language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t flabio/docker-react-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true flabio/docker-react-ci npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-ci"
  env: "DockerReactCi-env"
  bucket_name: "elasticbeanstalk-us-east-2-587547940751"
  bucket_path: "docker-react-ci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
